import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navbar */}
        <Navbar></Navbar>
        {/* outlet content */}
        <main className="min-h-96 place-content-center place-items-center">{children}</main>
        {/* footer */}
        <footer className="flex place-items-center place-content-center border-2 border-amber-100"> Awesome next js app </footer>
      </body>
    </html>
  );
}
